name: Release ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x ".git/*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
